# Generated by Django 4.1.5 on 2023-01-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clente',
            name='mail',
            field=models.EmailField(default=2, max_length=254),
            preserve_default=False,
        ),
    ]
