# Generated by Django 4.1.5 on 2023-01-30 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_clente_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clente',
            name='cumple',
        ),
    ]
