# Generated by Django 4.1.5 on 2023-02-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_cliente_delete_clente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=40)),
                ('color', models.CharField(max_length=40)),
            ],
        ),
    ]
