# Generated by Django 4.1.5 on 2023-02-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_prods'),
    ]

    operations = [
        migrations.CreateModel(
            name='nuevoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=40)),
                ('cantidad', models.IntegerField()),
                ('color', models.CharField(max_length=30)),
            ],
        ),
    ]
