# Generated by Django 4.1.5 on 2023-02-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0006_nuevopedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('producto', models.CharField(max_length=40)),
                ('cantidad', models.IntegerField()),
                ('color', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='nuevoPedido',
        ),
    ]
