# Generated by Django 4.1.5 on 2023-02-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0007_pedido_delete_nuevopedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='prods',
            name='nombre',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
