# Generated by Django 4.1.5 on 2023-02-25 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0009_prods_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prods',
            name='imagen',
            field=models.ImageField(blank=True, default='-', upload_to='productospedidos'),
        ),
    ]
